routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ERROR: Cannot use Illuminate\Support\Facades\Route as Route because the name is already in use
//use Illuminate\Support\Facades\Route;
//use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

// Register login, register, password-reset, and other lovely core stuff.
Auth::routes();

Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');
Route::get('register/to/{city_slug}/{section_id}', 'Auth\RegisterController@sectionPreload')->name('register.tosection');

Route::get('thanks/member-fee/paypal', 'App\Http\Controllers\ThanksController@paidMemberFeeViaPayPal')->name('thanks.member-fee.paypal');
Route::get('thanks/donation/paypal', 'App\Http\Controllers\ThanksController@paidDonationViaPayPal')->name('thanks.donation.paypal');

// **** developer stuff ****************************

Route::prefix('dev')->group(function () {

    // Allow to easily preview some internal pages without the need of complicated reproduce steps.
    Route::get('demo/oauth/authorize',
        [App\Http\Controllers\Dev\Demos::class, 'oauthAuthorize']
    )->name('dev.preview.oauth.authorize');

    // We support useful but very-dangerous auto-login workflows,
    // but first, you MUST have:
    //  - environment: local
    //  - env UNSAFE_QUICK_LOGIN_BACKDOOR: 1
    if (!app()->environment('local') || !env('DEV_QUICK_LOGIN_BACKDOOR')) {
        return;
    }

    Route::prefix('login')->group(function () {

        Route::get('admin', function () {
            $user = User::active()->ofRole('admin')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.admin');

        Route::get('member', function () {
            $user = User::active()->ofRole('member')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.member');

        Route::get('referent', function () {
            $user = User::active()->ofRole('referent')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.referent');

        Route::get('pending', function () {
            $user = User::pendingWithPaidFee()->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.pending');

        Route::get('suspended', function () {
            $user = User::ofStatus('suspended')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.suspended');

        Route::get('expelled', function () {
            $user = User::ofStatus('expelled')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.expelled');

        Route::get('dropped', function () {
            $user = User::ofStatus('dropped')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.dropped');

        Route::get('association', function () {
            $user = User::actLikeMember()
              ->ofType('association')->first();
            auth()->login(User::find($user->id));

            return redirect()->route('home');
        })->name('dev.login.association');

        Route::get('limited', function () {
            $user = User::ofType('limited')->first();
            auth()->login($user);
            return redirect()->route('home');
        })->name('dev.login.limited');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refresh/{id}', 'MovementController@refresh')->name('movement.refresh');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/{id}/download/{file}', 'MovementController@download')->name('movement.download');

    Route::get('movement-detailed/export/all/csv', 'MovementDetailedController@exportAllCsv')->name('movement-detailed.export.all.csv');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');
    Route::post('section/{id}/exportmembers', 'SectionController@exportmembers')->name('section.exportmembers');

    Route::get('refund/{id}/download/quote/{file}', 'RefundController@downloadQuote')->name('refund.quote.download');
    Route::get('refund/{id}/download/receipt/{file}', 'RefundController@downloadReceipt')->name('refund.receipt.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');
    Route::get('doc/link', 'DocumentationController@link')->name('doc.link');
    Route::get('doc/preview', 'DocumentationController@preview')->name('doc.preview');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

   // Route::get('bank/list/', 'BankController@list')->name('bank.list_all');
   // Route::get('bank/list/{id}', 'BankController@list')->name('bank.list');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('movement-detailed', 'MovementDetailedController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
    Route::resource('gadget-request', 'GadgetRequestController');
});

// Rotte per gli utenti ospiti
Route::get('gadget-request-track/{token}', 'GadgetRequestController@showByToken')->name('gadget-request.show-by-token');
Route::get('gadget-request-thank-you', 'GadgetRequestController@thankYou')->name('gadget-request.thank-you');
Route::get('gadget-request/create', 'GadgetRequestController@create')->name('gadget-request.create');
Route::post('gadget-request/store', 'GadgetRequestController@store')->name('gadget-request.store');

// Useful public pages
Route::get('page/how-to-pay', 'PageController@howToPay')->name('page.how-to-pay');

app/Http/Controllers/GadgetRequestController.php
<?php

namespace App\Http\Controllers;

use App\GadgetRequest;
use App\GadgetRequestStatus;
use App\GadgetType;
use Auth;
use Illuminate\Http\Request;

class GadgetRequestController extends EditController
{
    public function __construct()
    {
        parent::init([
            'classname' => GadgetRequest::class,
            'view_folder' => 'gadget-request',
        ]);

        // No feature, no party.
        if( !GadgetRequest::is_feature_enabled()) {
            abort(404);
        }
    }

    /**
     * Create a new, un-persisted, object.
     */
    protected function createObject(Request $request)
    {
        $object = new GadgetRequest;
        if (Auth::check()) {
            $auth_user = Auth::user();
            $object->user_id = $auth_user->id;
            $object->name = $auth_user->name;
            $object->surname = $auth_user->surname;
            $object->street = $auth_user->shipping_street ?? $auth_user->address_street;
            $object->postal_code = $auth_user->shipping_zip ?? $auth_user->address_zip;
            $object->province = $auth_user->shipping_prov ?? $auth_user->address_prov;
            $object->city = $auth_user->shipping_place ?? $auth_user->address_place;
        }
        return $object;
    }

    /**
     * Create a Query object, with default order.
     */
    protected function queryList(Request $request)
    {
        $query = parent::queryList($request)
            ->with('status')
            ->with('user');

        $args = $this->getExtraFilterArguments($request);
        if ($args['selected_status_ids']) {
            $query->whereIn('status_id', $args['selected_status_ids']);
        }

        // Show my stuff.
        if ($args['my_requests'] === '1' && Auth::check()) {
            $query->where('user_id', Auth::user()->id);
        }

        return $query;
    }

    public function getIndexArguments(Request $request)
    {
        $args = array_merge(
            parent::getIndexArguments($request),
            $this->getExtraFilterArguments($request)
        );

        // Show a multi-tracking URL, if possible.
        // This is shown to everybody, if you can see all details.
        $args['multi_tracking_url'] = null;
        if (Auth::check()) {
            $tracking_codes = [];
            foreach ($args['objects'] as $object) {
                if (Auth::check() && $object->tracking_code && Auth::user()->can('view', $object)) {
                    $tracking_codes[] = $object->tracking_code;
                }
            }
            if ($tracking_codes) {
                $args['multi_tracking_url'] =
                    GadgetRequest::postal_multi_tracker_URL($tracking_codes);
            }
        }

        return $args;
    }

    /**
     * Get filters in use by the page and shown in the index view.
     */
    private function getExtraFilterArguments(Request $request)
    {
        $args['all_statuses'] = GadgetRequestStatus::all();
        $args['gadgetTypes'] = GadgetType::where('is_active', true)->get();

        $selected_status_uids = $request->input('status');

        // Show a default filter by status.
        if (!is_array($selected_status_uids)) {
            // TODO: Add an option "Is default filter" in table "gadget_request_statuses".
            //       So we don't hardcode database stuff here.
            //       Nobody probably will ever do this. That's OK. -2024-11-12 -bozz
            $selected_status_uids = GadgetRequestStatus::getActiveStatusUIDs();
        }

        $args['selected_status_ids'] = [];
        foreach ($selected_status_uids as $selected_status_uid) {
            $args['selected_status_ids'][] = GadgetRequestStatus::findByUID($selected_status_uid)->id;
        }

        // Whenever we should only show my stuff.
        $args['my_requests'] = $request->input('my_requests', $this->getDefaultFilterMyRequests());

        return $args;
    }

    public function thankYou()
    {
        return view($this->view_folder . '.thank_you');
    }

    public function create(Request $request)
    {
        // This is the creation form for anonymous people.
        return view($this->view_folder . '.create', $this->getIndexArguments($request));
    }

    public function store(Request $request)
    {
        $this->authorize('create', $this->classname);
        $validations = $this->defaultValidations(null);
        $request->validate($validations);

        $object = new $this->classname;
        $this->requestToObject($request, $object);
        $object->save();
        $this->afterSaving($request, $object);

        if (Auth::check()) {
            return redirect()->route('gadget-request.index')
                ->with('success', 'Richiesta di gadget creata con successo.');
        }

        return redirect()->route('gadget-request.thank-you')
            ->with('success', 'Richiesta di gadget creata con successo.');
    }

    public function getEditArguments($id)
    {
        // Imita parent
        $args = parent::getEditArguments($id);

        // Recupera i tipi di gadget attivi
        $args['gadgetTypes'] = GadgetType::where('is_active', true)->get();

        // Passa la richiesta e i tipi di gadget alla vista
        return $args;
    }

    // Controller method to handle fetching the request by token
    public function showByToken($token)
    {
        $gadgetRequest = GadgetRequest::where('token', $token)->firstOrFail();

        return view($this->view_folder . '.show', [ "gadgetRequest" => $gadgetRequest ]);
    }

    protected function defaultValidations($object)
    {
        return [
            'email' => 'nullable|email',
            'name' => 'required|string|max:255',
            'surname' => 'required|string|max:255',
            'postal_code' => 'required|string|max:10',
            'city' => 'required|string|max:255',
            'province' => 'required|string|max:255',
            'street' => 'required|string|max:255',
            'distribution_location' => 'nullable|string',
            'subscribe_newsletter' => 'boolean',
            'gadget_type' => 'required|array',
            'gadget_type.*' => 'integer|exists:gadget_types,id', // Validazione di ogni elemento dell'array
            'status_id' => 'nullable|string|in:' . implode(',', GadgetRequestStatus::pluck('id')->toArray()),
        ];
    }

    protected function requestToObject(Request $request, $object): void
    {
        $object->name = $request->input('name');
        $object->surname = $request->input('surname');
        $object->street = $request->input('street');
        $object->postal_code = $request->input('postal_code');
        $object->city = $request->input('city');
        $object->province = $request->input('province');
        $object->distribution_location = $request->input('distribution_location');
        $object->subscribe_newsletter = $request->input('subscribe_newsletter');
        if (!isset($object->id)) {
            // Creation

            if (Auth::check()) {
                // Registered user.
                // Create as valid as default.
                $object->user_id = Auth::id();
                $object->email = null;
                $object->status_id = GadgetRequestStatus::findByUID('valid')->id;
            } else {
                // Unregistered user.
                // Create as pending as default.
                $object->email = $request->input('email');
                $object->status_id = GadgetRequestStatus::findByUID('pending')->id;
            }
        } else {
            // Update

            // Only allow unregistered users to set/update the email.
            if ($object->user_id) {
                $object->email = null;
            } else {
                $object->email = $request->input('email');
            }

            // Allow shipper and admins to review.
            if (Auth::user()->can('review', $object)) {
                $object->status_id     = $request->input('status_id',     $object->status_id);
                $object->tracking_code = $request->input('tracking_code', $object->tracking_code);
            }
        }
    }

    protected function afterSaving($request, $object)
    {
        $gadgetTypeIds = $request->input('gadget_type', []);
        $object->gadgetTypes()->sync($gadgetTypeIds);
    }

    protected function defaultSortingColumn()
    {
        return 'id';
    }

    /**
     * Get the default filter for the "my requests" filter.
     * @return string
     */
    private function getDefaultFilterMyRequests()
    {
        // Reviewers and admins may want to see everything as default.
        if (Auth::check() && Auth::user()->can('review', new GadgetRequest)) {
            return '0';
        }

        // Normal users may want to only see their stuff.
        return '1';
    }

}

resources/views/gadget-request/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Nuova Richiesta di Spedizione Gadget</h1>

        <div>
            <p>Potremmo avere ancora a disposizione qualche gadget da poter spedire direttamente a casa tua (o ad un indirizzo di spedizione comodo per te) a spese nostre.</p>
            <p>Ti ringraziamo per il tuo aiuto nel diffondere questi materiali nelle tue cerchie. Ricordati che la maggior parte dei materiali
               che riceverai è progettato, prodotto e spedito nel nostro tempo libero, e a spese nostre, da persone volontarie.
               Grazie per il tuo tempo per valorizzare al meglio questi materiali.</p>
            <p>Compila i dati della tua richiesta di spedizione. Inserisci un tuo indirizzo di ricezione valido.</p>
        </div>

        <form action="{{ route('gadget-request.store') }}" method="POST">
            @csrf

            @include('gadget-request.form', ['object' => $default_object, 'gadgetTypes' => $gadgetTypes])

            <button type="submit" class="btn btn-primary">Invia Richiesta</button>
        </form>
    </div>
@endsection

resources/views/gadget-request/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form method="POST" action="{{ route('gadget-request.update', $object->id) }}" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf

                    @include('gadget-request.form', ['object' => $object])

                    @if($object)
                        <h3>Stato attuale</h3>
                        <div class="form-group row">
                            <label for="status_id" class="col-sm-4 col-form-label">Stato</label>
                            <div class="col-sm-8">
                                @can('review', $object)
                                    <select class="form-control" id="status_id" name="status_id">
                                        @foreach(\App\GadgetRequestStatus::all() as $status)
                                            <option value="{{ $status->id }}" @selected($status->id == $object->status_id)>{{ $status->label }}</option>
                                        @endforeach
                                    </select>
                                    <p>Attenzione: cambiando il campo dello stato attuale, l'utenza riceverà una notifica informativa.</p>
                                @else
                                    <input type="text" value="{{ $object->status->label }}" readonly disabled>
                                @endcan
                            </div>
                        </div>

                        <h3>Spedizione</h3>

                        @can('view', $object)
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Indirizzo generato sulla busta</label>
                            <div class="col-sm-8">
                                <div class="card">
                                    <pre>{{ $object->shippingAddressRaw }}</pre>
                                </div>
                            </div>
                        </div>
                        @endcan

                        <div class="form-group row">
                            <label for="status_id" class="col-sm-4 col-form-label">Codice di tracciamento</label>
                            <div class="col-sm-8">
                                @can('review', $object)
                                    <input type="text" name="tracking_code" value="{{ $object->tracking_code }}">
                                @else
                                    <input type="text" value="{{ $object->tracking_code }}" readonly disabled>
                                @endcan
                            </div>
                        </div>
                    @endif

                    <hr>

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Salva</button>
                        </div>
                    </div>
                </form>

                <br>

                <form method="POST" action="{{ route('gadget-request.destroy', $object->id) }}">
                    @method('DELETE')
                    @csrf

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-danger{{ Auth::user()->can('delete', $object ) ? '' : ' disabled' }}">Elimina Richiesta di Gadget</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/gadget-request/form.blade.php
<h2>Richiesta di Gadget</h2>

<div class="form-group row">
    <label for="name" class="col-sm-4 col-form-label">Nome</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" id="name" name="name" value="{{ $object ? $object->name : '' }}" required>
    </div>
</div>

<div class="form-group row">
    <label for="surname" class="col-sm-4 col-form-label">Cognome</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" id="surname" name="surname" value="{{ $object ? $object->surname : '' }}" required>
    </div>
</div>

@if (!Auth::user() || ($object && $object->email))
    <div class="form-group row">
        <label for="gadget-email" class="col-sm-4 col-form-label">Email</label>
        <div class="col-sm-8">
            <input type="email" class="form-control" id="gadget-email" name="email" value="{{ $object ? $object->email : '' }}" required>
        </div>
    </div>
@endif

<div class="form-group row">
    <label for="street" class="col-sm-4 col-form-label">Indirizzo e numbero civico</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" id="street" name="street" value="{{ $object ? $object->street : '' }}" required>
    </div>
</div>

<div class="form-group row">
    <label for="postal_code" class="col-sm-4 col-form-label">CAP</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" id="postal_code" name="postal_code" value="{{ $object ? $object->postal_code : '' }}" required pattern="[0-9]{5}">
    </div>
</div>

<div class="form-group row">
    <label for="city" class="col-sm-4 col-form-label">Città</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" id="city" name="city" value="{{ $object ? $object->city : '' }}" required>
    </div>
</div>

<div class="form-group row">
    <label for="province" class="col-sm-4 col-form-label">Provincia</label>
    <div class="col-sm-8">
        @include('commons.provinces', [
            'name' => 'province',
            'id' => 'province',
            'value' => $object ? $object->province : null,
            'required' => true,
        ])
    </div>
</div>

<div class="form-group row">
    <label for="distribution_location" class="col-sm-4 col-form-label">Luogo di Distribuzione</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" id="distribution_location" name="distribution_location" value="{{ $object ? $object->distribution_location : '' }}" placeholder="Scuola, ufficio, ecc.">
    </div>
</div>

<div class="form-group row">
    <label for="subscribe_newsletter" class="col-sm-4 col-form-label">Iscriviti alla Newsletter</label>
    <div class="col-sm-8">
        <input type="hidden" name="subscribe_newsletter" value="0">
        <input type="checkbox" class="form-control" id="subscribe_newsletter" name="subscribe_newsletter" value="1" {{ $object && $object->subscribe_newsletter ? 'checked' : '' }}>
    </div>
</div>

<div class="form-group row">
    <label for="gadget_type" class="col-sm-4 col-form-label">Tipo di Gadget</label>
    <div class="col-sm-8">
        @foreach($gadgetTypes as $gadgetType)
            <div class="form-check" id="gadget_type">
                <input class="form-check-input" type="checkbox" name="gadget_type[]" value="{{ $gadgetType->id }}" id="gadget_type_{{ $gadgetType->id }}"
                    @checked( isset($object->id) ? $object->gadgetTypes->contains($gadgetType->id) : $gadgetType->is_default )
                >
                <label class="form-check-label" for="gadget_type_{{ $gadgetType->id }}">
                    {{ $gadgetType->name }}
                </label>
            </div>
        @endforeach
    </div>
</div>

resources/views/gadget-request/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createGadgetRequest">Nuova Richiesta Gadget</button></p>
                <div class="modal fade" id="createGadgetRequest" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Nuova Richiesta Gadget</h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <span>&times;</span>
                                </button>
                            </div>
                            <form method="POST" action="{{ route('gadget-request.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="modal-body">
                                    @include('gadget-request.form', ['object' => $default_object])
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                                    <button type="submit" class="btn btn-primary">Salva</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <form method="GET" action="" class="auto-filter-form">
            <div class="row mt-12">
                <div class="col-md-12 col-lg-6">
                    <div class="form-group">
                        <label for="status">Stato:</label>
                        @foreach($all_statuses as $status)
                            <div>
                                <input id="status-{{ $status->uid }}" type="checkbox" name="status[]" value="{{ $status->uid }}" @checked(in_array($status->id, $selected_status_ids))>
                                <label for="status-{{ $status->uid }}" class="tip" title="{{ $status->description }}">{{ $status->label }}</label>
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="col-md-12 col-lg-6">
                    <div class="form-group">
                        <label for="my-requests">Richiedente:</label>
                        <select name="my_requests" id="my-requests" class="form-control">
                            <option value="0" @selected($my_requests !== '1')>Chiunque</option>
                            <option value="1" @selected($my_requests === '1')>Me</option>
                        </select>
                    </div>
                </div>
            </div>
        </form>

        <div class="row mt-3">
            <div class="col-md-12">

                @if($currentuser->hasRole(['admin', 'shipper']))
                    <p>In qualità di amministratore puoi vedere tutte le richieste di spedizione. Non diffondere questi dati personali senza l'autorizzazione della persona interessata.</p>
                @else
                    <p>Puoi vedere le tue richieste ed eventuali altre richieste anonimizzate.</p>
                @endif

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Data Richiesta</th>
                        <th>Richiedente</th>
                        <th>Email</th>
                        <th>Gadget</th>
                        <th>Stato</th>
                        <th>Dettagli</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($objects as $object)
                        <tr>
                            <td>{{ $object->id }}</td>
                            <td>{{ $object->created_at }}</td>
                            @can('view', $object)
                            <td><pre>{{ $object->shippingAddressRaw }}</pre>
                                @if ($object->isCurrentUserAuthor())
                                    <br />
                                    <em>(mia richiesta)</em>
                                @endif
                            </td>
                            <td>{{ $object->whateverEmail }}</td>
                            @else
                                    <td><em>omissis</em><br />
                                        <em title="Provincia di {{ $object->province }}">{{ $object->province }}</em>
                                    </td>
                                    <td><em>omissis</em></td>
                            @endcan
                            <td>
                                @foreach($object->gadgetTypes as $gadgetType)
                                    <span class="badge badge-info">{{ $gadgetType->name }}</span>
                                @endforeach
                                @if ($object->gadgetTypes->isEmpty())
                                    <em>nessuno</em>
                                @endif
                            </td>
                            <td>{{ $object->status->label }}</td>
                            <td>
                                <a href="{{ route('gadget-request.edit', $object->id) }}" class="btn {{ auth()->user()->can('update', $object) ? '' : 'disabled' }}"><i class="fa-solid fa-pencil"></i></a>

                                @if ($object->tracking_code)
                                    @can('view', $object)
                                    <a href="{{ $object->postalTrackerURL }}" class="btn" target="_blank" title="Traccia spedizione {{ $object->tracking_code }}"><i class="fa-solid fa-map"></i></a>
                                    @endcan
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                @if ($multi_tracking_url)
                <div>
                    <p><a href="{{ $multi_tracking_url }}" class="btn" target="_blank"><i class="fa-solid fa-globe"></i> Traccia le spedizioni</a></p>
                </div>
                @endif

                {{ $objects->links() }}
            </div>
        </div>
    </div>
@endsection